[features]
seeds = false

[programs.localnet]
solana_twitter = "78ummy2JP8DzTJVvN6eHAsYMrxrft8orFncAJubVxVmn"

[programs.devnet]
solana_twitter = "78ummy2JP8DzTJVvN6eHAsYMrxrft8orFncAJubVxVmn"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/Brandon/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"
my-custom-script = "echo 'tests ran from Anchor.toml!'"